//import java.util.Random;

public class CodeMaker {

	// Initialize el random
	//Random random=new Random();
	//char[] SecretCodearray = new char[4];

	// A member variable of Code to store the secret code
	private Code secretCode;
	// getter of secretCode

	public Code getSecretCode() {
		
		return secretCode; // with this instruction return the char array with the secret code 
						  // this secret code is doing inside the method makesecretcode inside that 
						 // Using the class code method Make RandomCode	

	}

	// setter of secretCode
	public void setSecretCode(Code secretCode) { 
		this.secretCode = secretCode;  //With this Method you bring the information of this variable into the this class

	}

	// default constructor
	public CodeMaker() {
	}

	// this method generate the secret code and store the secret code
	// in the member variable secretCode. The secret code generated will
	// not have duplicated pegs. For example, it is not allowed to have
	// the secret code "R P P O" because "P" is a duplicate.
	public void makeSecretCode() {
		Code code=new Code();
		while(code.hasDuplicatedPegs()) code.makeRandomCode();// using the class code method hasDuplicatePegs
															 //	Check is exist duplicates compare the array pegs generated by code.makeRandomCode()
															// if exist duplicates the random generation work again, if not continue	
														   // makeRandomCode method using a class Math.Random it function assign a random number between mayor or equal to 0 to less than 1 
														  // after that multiply for 6 assign one random number between 0 to 5 and in the variable  array char Colors are the storage all colors
													     // with the method setcolor it return the exactly position between 0 to 5 with the color and assign in array pegs
		                                                    
		secretCode=new Code(code.getPeg(0),code.getPeg(1),code.getPeg(2),code.getPeg(3)); // Using this method inside code assign the variables random generated 
																						  // and storage in pegs to the secretcode using the method Code with four char input
		

	}
}
